[control]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

#EC2나 Tailscale Subnet Router에서 실행할 거면 아래코드로 수정

#[control]
#admin-host ansible_host=YOUR_ADMIN_HOST_IP ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3