apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dr-web
  template:
    metadata:
      labels:
        app: dr-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dr-web-service
spec:
  selector:
    app: dr-web
  ports:
  - port: 80
    targetPort: 80
  type: NodePort