apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  # 부하 증가 시 자동으로 추가 노드를 만들기 위한 NodePool
  name: dr-nodepool

spec:
  template:
    metadata:
      labels:
        workload: dr

    spec:
      # 어떤 AWS 노드 설정을 사용할지 지정
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: dr-ec2-nodeclass

      requirements:
        # 온디맨드 인스턴스를 사용하여 예측 가능한 운영을 유지
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

        # x86_64 아키텍처 사용
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        # t 계열 인스턴스 사용
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]

        # 너무 작은 micro는 제외하고 small, medium 중심으로 제한
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium"]

  limits:
    # 비용 통제를 위해 NodePool 전체 최대 CPU를 보수적으로 제한
    cpu: "4"

  disruption:
    # 유휴 노드는 통합 대상으로 보고, 너무 빠른 축소는 피하도록 약간 여유 둬야함
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 60s